server:
  shutdown: immediate

core:
  attachment:
    host:
      download: "https://apicongthuong.danang.gov.vn/v2/core"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/core_sys_service
    password: SctPro@123
  data:
    redis:
      password: "SctPro@123"
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0

redisson:
  keyPrefix: "tr"
  singleServerConfig:
    clientName: ${app.name}
