core:
  attachment:
    host:
      download: ${CORE_ATTACHMENT_HOST_DOWNLOAD:'https://mcdtqa.danang.gov.vn/api/v2/core'}
    path:
      upload: ${CORE_ATTACHMENT_PATH_UPLOAD:/opt/uploads}
      uploadtemp: ${CORE_ATTACHMENT_PATH_UPLOADTEMP:/opt/uploads/temp}
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://mcdt-postgres:5432/mcdt_core_service}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:DnictPro@123}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
client:
  notification-service:
    url: ${CLIENT_NOTIFICATION_SERVICE_URL:http://mcdt-gateway:8000/v1/notification}
