core:
  attachment:
    host:
      download: "http://49.156.54.41:8000/v2/core"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/core_sys_service
    password: HdndPro@123
  data:
    redis:
      password: "HdndPro@123"
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0

redisson:
  keyPrefix: "tr"
  singleServerConfig:
    clientName: ${app.name}
