core:
  attachment:
    host:
      download: "https://csdlgtvt.danang.gov.vn:8080/v2/core"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/core_sys_service
    password: SgtvtPro@123
  data:
    redis:
      password: "SgtvtPro@123"
