spring:
  datasource:
    password: Abc@123
  data:
    redis:
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
  devtools:
    restart:
      enabled: false

captcha:
  enable: false

redisson:
  keyPrefix: "tr"
  singleServerConfig:
    clientName: ${app.name}
