core:
  attachment:
    host:
      download: "https://danhgiacntt.danang.gov.vn/api/v2/core"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tr-core-service
    password: 123456
  data:
    redis:
      password: "DanhGiaCntt@123"
